Trove Guest Agent build files and Xenial support  Please enter the commit message for your changes. Lines starting
Change-Id: Ie585bd8b32ea147fa790232f56422d0c7f25bbec

diff --git a/integration/scripts/files/elements/ubuntu-xenial-mysql/install.d/30-mysql b/integration/scripts/files/elements/ubuntu-xenial-mysql/install.d/30-mysql
--- a/integration/scripts/files/elements/ubuntu-xenial-mysql/install.d/30-mysql
+++ b/integration/scripts/files/elements/ubuntu-xenial-mysql/install.d/30-mysql
@@ -6,12 +6,12 @@
 set -e
 set -o xtrace
 
+#apt-get install -y debconf-utils
+
 export DEBIAN_FRONTEND=noninteractive
 
-add-apt-repository 'deb http://archive.ubuntu.com/ubuntu trusty universe'
-apt-get -y  update
 
-apt-get --allow-unauthenticated -y install mysql-client-5.6 mysql-server-5.6 percona-xtrabackup${PXB_VERSION_OVERRIDE}
+apt-get  --allow-unauthenticated -y install mysql-client-5.6 mysql-server-5.6 percona-xtrabackup
 
 cat >/etc/mysql/conf.d/no_perf_schema.cnf <<_EOF_
 [mysqld]
@@ -22,11 +22,73 @@ mv /etc/mysql/my.cnf.fallback /etc/mysql/my.cnf
 chown mysql:mysql /etc/mysql/my.cnf
 cat >/etc/mysql/my.cnf <<_EOF_
 [mysql]
-
 !includedir /etc/mysql/conf.d/
 _EOF_
 
-rm /etc/init/mysql.conf
+cat >/lib/systemd/system/mysql.service <<_EOF_
+# MySQL systemd service file
+
+[Unit]
+Description=MySQL Community Server
+After=network.target
+
+[Install]
+WantedBy=multi-user.target
+
+[Service]
+User=mysql
+Group=mysql
+PermissionsStartOnly=true
+ExecStartPre=/usr/share/mysql/mysql-systemd-start pre
+ExecStart=/usr/sbin/mysqld
+ExecStartPost=/usr/share/mysql/mysql-systemd-start post
+TimeoutSec=600
+Restart=on-failure
+RuntimeDirectory=mysqld
+RuntimeDirectoryMode=755
+_EOF_
+
+cat >/usr/share/mysql/mysql-systemd-start <<'_EOF_'
+#!/bin/bash
+#
+# Scripts to run by MySQL systemd service
+#
+# Needed argument: pre | post
+#
+# pre mode  :  try to perform sanity check for configuration, log, data
+# post mode :  ping server until answer is received
+
+sanity () {
+  if [ ! -r /etc/mysql/my.cnf ]; then
+    echo "MySQL configuration not found at /etc/mysql/my.cnf. Please create one."
+    exit 1
+  fi
+}
+
+pinger () {
+  server_up=false
+  for i in $(seq 1 30); do
+    sleep 1
+    if mysqladmin ping >/dev/null 2>&1; then
+      server_up=true
+      break
+    fi
+  done
+  if [ ! $server_up ]; then
+    echo "MySQL server not started"
+    exit 1
+  fi
+}
+
+case $1 in
+  "pre")  sanity ;;
+  "post") pinger ;;
+esac
+_EOF_
+
+chmod 0755 /usr/share/mysql/mysql-systemd-start
+
+rm -rf /etc/init/mysql.conf
+rm -rf /etc/init.d/mysql
 systemctl daemon-reload
 systemctl enable mysql
-
